const SEARCH = "SEARCH";
const LETTERS = "LETTERS";
const LOADING = "LOADING";
const PAGE = "PAGE";
const RESET = "RESET";
const INDEX = "INDEX";
const CHARACTER_DETAIL = "CHARACTER_DETAIL";
const INDEX_BTN = "INDEX_BTN";

const FILTER_ALPH = "FILTER_ALPH";
const FILTER_GENDER = "FILTER_GENDER";
const FILTER_HOMEWORLD = "FILTER_HOMEWORLD";
const LOADING_DETAIL = "LOADING_DETAIL";

export {
  SEARCH,
  LETTERS,
  LOADING,
  LOADING_DETAIL,
  PAGE,
  RESET,
  INDEX,
  INDEX_BTN,
  CHARACTER_DETAIL,
  FILTER_ALPH,
  FILTER_GENDER,
  FILTER_HOMEWORLD,
};
